//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLab1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группа()
        {
            this.Студенты_в_группах = new HashSet<Студент_в_группе>();
        }
    
        public System.Guid ID_группы { get; set; }
        public System.Guid ID_института { get; set; }
        public string Наименование { get; set; }
        public int Год_поступления { get; set; }
        public int Длительность_обучения { get; set; }
        public int Код_формы_обучения { get; set; }
        public string Код_направления_подготовки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент_в_группе> Студенты_в_группах { get; set; }
    }
}
