//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLab1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Студент()
        {
            this.Студенты_в_группах = new HashSet<Студент_в_группе>();
        }
    
        public System.Guid ID_студента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public bool Пол { get; set; }
        public string Адрес_проживания { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Уровень_владения_ИЯ { get; set; }
        public System.Guid Id_пользователя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент_в_группе> Студенты_в_группах { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
